const Joi = require('joi-browser')
const phoneValidator = require('joi-phone-validator')

module.exports = {
  userSchema: Joi.object().keys({
    email: Joi.string().lowercase().email().required(),
    firstName: Joi.string().min(3).required(),
    lastName: Joi.string().min(3).required(),
    uuid: Joi.string().guid({ version: ['uuidv4', 'uuidv5'] }).required(),
    address: Joi.string().allow('').optional(),
    city: Joi.string().allow('').optional(),
    country: Joi.string().allow('').optional(),
    phone: phoneValidator.phone().required(),
    docType: Joi.string().allow('').optional(),
    docNo: Joi.string().allow('').optional(),
    userZip: Joi.string().allow('').optional(),
    dob: Joi.date().required(),
    addressDocument: Joi.string().allow('').optional(),
    idDocument: Joi.string().allow('').optional(),
    agreeToS: Joi.boolean().optional(),
    agreeToICOs: Joi.boolean().optional(),
    agreeToAirdrops: Joi.boolean().optional()
  }).with('email', ['firstName', 'lastName', 'uuid', 'address', 'city',
    'country', 'phone', 'docType', 'docType', 'docNo', 'userZip', 'dob', 'addressDocument',
    'idDocument', 'agreeToS', 'agreeToICOs', 'agreeToAirdrops']),

  companySchema: Joi.object().keys({
    company: Joi.string().min(5).required(),
    companyAddress: Joi.string().required(),
    companyCity: Joi.string().required(),
    companyZip: Joi.string().required(),
    companyCountry: Joi.string().required(),
    companyRegDoc: Joi.string().required(),
    logo: Joi.string().allow('').optional(),
    shortDescription: Joi.string().max(250).allow('').optional(),
    projectDescription: Joi.string().max(2000).allow('').optional(),
    video: Joi.string().uri().allow('').optional(),
    startDate: Joi.string().allow('').optional(),
    endDate: Joi.string().allow('').optional(),
    website: Joi.string().uri().allow('').optional(),
    whitepaper: Joi.string().uri().allow('').optional(),
    facebook: Joi.string().uri().allow('').optional(),
    twitter: Joi.string().allow('').optional(),
    telegram: Joi.string().allow('').optional(),
    medium: Joi.string().allow('').optional(),
    bitcoinTalk: Joi.string().uri().allow('').optional(),
    reddit: Joi.string().uri().allow('').optional(),
    slack: Joi.string().allow('').optional(),
    hardCap: Joi.number().allow('').optional(),
    softCap: Joi.number().allow('').optional(),
    type: Joi.string().allow('').optional(),
    tokenDistribution: Joi.string().allow('').optional(),
    tokenSymbol: Joi.string().max(5).allow('').optional(),
    initialPrice: Joi.number().allow('').optional(),
    kyc: Joi.number().allow('').optional(),
    restrictions: Joi.string().allow('').optional(),
    accepts: Joi.string().allow('').optional(),
    team: Joi.string().allow('').optional()
  }).with('company', ['companyAddress', 'companyCity', 'companyZip', 'companyCountry', 'companyRegDoc']),

  privacyRules: [
    { label: 'Allow to view for public', value: 'allow_view_public' },
    { label: 'Allow to view for managers', value: 'allow_view_manager' },
    { label: 'Allow invites from ICOs', value: 'allow_invite_ico' },
    { label: 'Allow invites from Airdrops', value: 'allow_invite_airdrop' },
    { label: 'Private', value: 'private' }
  ],

  validationRules: [
    { label: 'Age > 18', value: 'age_18' },
    { label: 'Not from banned for ICO country', value: 'banned_ico_country' },
    { label: 'Has full ID verification', value: 'full_id' }
  ],

  dirTypes: [
    { label: 'ICO', value: 'ico' },
    { label: 'Airdrop', value: 'airdrop' }
  ],

  kycReq: [
    { label: 'Yes', value: '1' },
    { label: 'No', value: '0' }
  ],

  acceptedCurr: [
    { label: 'ETH', value: 'ETH' },
    { label: 'BTC', value: 'BTC' },
    { label: 'LTC', value: 'LTC' },
    { label: 'BCC', value: 'BCC' },
    { label: 'XRP', value: 'XRP' }
  ],

  docTypes: [
    { label: 'Passport', value: 'Passport' },
    { label: 'Personal ID', value: 'Personal ID' },
    { label: 'Driver\'s licence', value: 'Driver\'s licence' }
  ],

  roles: [
    { value: 0, label: 'Default' },
    { value: 1, label: 'Admin' },
    { value: 2, label: 'Manager' },
    { value: 3, label: 'SuperAdmin' }
  ],

  userStates: [
    { value: 0, label: 'Waiting' },
    { value: 1, label: 'Approved' },
    { value: 2, label: 'Disapproved' },
    { value: 3, label: 'Reportable' }
  ],

  countries: [
    { value: 'Afghanistan', label: 'Afghanistan' },
    { value: 'Albania', label: 'Albania' },
    { value: 'Algeria', label: 'Algeria' },
    { value: 'Andorra', label: 'Andorra' },
    { value: 'Angola', label: 'Angola' },
    { value: 'Anguilla', label: 'Anguilla' },
    { value: 'Antigua & Barbuda', label: 'Antigua & Barbuda' },
    { value: 'Argentina', label: 'Argentina' },
    { value: 'Armenia', label: 'Armenia' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Azerbaijan', label: 'Azerbaijan' },
    { value: 'Bahamas', label: 'Bahamas' },
    { value: 'Bahrain', label: 'Bahrain' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Barbados', label: 'Barbados' },
    { value: 'Belarus', label: 'Belarus' },
    { value: 'Belgium', label: 'Belgium' },
    { value: 'Belize', label: 'Belize' },
    { value: 'Benin', label: 'Benin' },
    { value: 'Bermuda', label: 'Bermuda' },
    { value: 'Bhutan', label: 'Bhutan' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Bosnia & Herzegovina', label: 'Bosnia & Herzegovina' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'Brazil', label: 'Brazil' },
    { value: 'Brunei Darussalam', label: 'Brunei Darussalam' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Burkina Faso', label: 'Burkina Faso' },
    { value: 'Myanmar/Burma', label: 'Myanmar/Burma' },
    { value: 'Burundi', label: 'Burundi' },
    { value: 'Cambodia', label: 'Cambodia' },
    { value: 'Cameroon', label: 'Cameroon' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Cape Verde', label: 'Cape Verde' },
    { value: 'Cayman Islands', label: 'Cayman Islands' },
    { value: 'Central African Republic', label: 'Central African Republic' },
    { value: 'Chad', label: 'Chad' },
    { value: 'Chile', label: 'Chile' },
    { value: 'China', label: 'China' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Comoros', label: 'Comoros' },
    { value: 'Congo', label: 'Congo' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Croatia', label: 'Croatia' },
    { value: 'Cuba', label: 'Cuba' },
    { value: 'Cyprus', label: 'Cyprus' },
    { value: 'Czech Republic', label: 'Czech Republic' },
    { value: 'Democratic Republic of the Congo', label: 'Democratic Republic of the Congo' },
    { value: 'Denmark', label: 'Denmark' },
    { value: 'Djibouti', label: 'Djibouti' },
    { value: 'Dominica', label: 'Dominica' },
    { value: 'Dominican Republic', label: 'Dominican Republic' },
    { value: 'Ecuador', label: 'Ecuador' },
    { value: 'Egypt', label: 'Egypt' },
    { value: 'El Salvador', label: 'El Salvador' },
    { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
    { value: 'Eritrea', label: 'Eritrea' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Ethiopia', label: 'Ethiopia' },
    { value: 'Fiji', label: 'Fiji' },
    { value: 'Finland', label: 'Finland' },
    { value: 'France', label: 'France' },
    { value: 'French Guiana', label: 'French Guiana' },
    { value: 'Gabon', label: 'Gabon' },
    { value: 'Gambia', label: 'Gambia' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Germany', label: 'Germany' },
    { value: 'Ghana', label: 'Ghana' },
    { value: 'Great Britain', label: 'Great Britain' },
    { value: 'Greece', label: 'Greece' },
    { value: 'Grenada', label: 'Grenada' },
    { value: 'Guadeloupe', label: 'Guadeloupe' },
    { value: 'Guatemala', label: 'Guatemala' },
    { value: 'Guinea', label: 'Guinea' },
    { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
    { value: 'Guyana', label: 'Guyana' },
    { value: 'Haiti', label: 'Haiti' },
    { value: 'Honduras', label: 'Honduras' },
    { value: 'Hungary', label: 'Hungary' },
    { value: 'Iceland', label: 'Iceland' },
    { value: 'India', label: 'India' },
    { value: 'Indonesia', label: 'Indonesia' },
    { value: 'Iran', label: 'Iran' },
    { value: 'Iraq', label: 'Iraq' },
    { value: 'Israel and the Occupied Territories', label: 'Israel and the Occupied Territories' },
    { value: 'Italy', label: 'Italy' },
    { value: 'Ivory Coast (Cote d\'Ivoire)', label: 'Ivory Coast (Cote d\'Ivoire)' },
    { value: 'Jamaica', label: 'Jamaica' },
    { value: 'Japan', label: 'Japan' },
    { value: 'Jordan', label: 'Jordan' },
    { value: 'Kazakhstan', label: 'Kazakhstan' },
    { value: 'Kenya', label: 'Kenya' },
    { value: 'Kosovo', label: 'Kosovo' },
    { value: 'Kuwait', label: 'Kuwait' },
    { value: 'Kyrgyz Republic (Kyrgyzstan)', label: 'Kyrgyz Republic (Kyrgyzstan)' },
    { value: 'Laos', label: 'Laos' },
    { value: 'Latvia', label: 'Latvia' },
    { value: 'Lebanon', label: 'Lebanon' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Liberia', label: 'Liberia' },
    { value: 'Libya', label: 'Libya' },
    { value: 'Liechtenstein', label: 'Liechtenstein' },
    { value: 'Lithuania', label: 'Lithuania' },
    { value: 'Luxembourg', label: 'Luxembourg' },
    { value: 'Republic of Macedonia', label: 'Republic of Macedonia' },
    { value: 'Madagascar', label: 'Madagascar' },
    { value: 'Malawi', label: 'Malawi' },
    { value: 'Malaysia', label: 'Malaysia' },
    { value: 'Maldives', label: 'Maldives' },
    { value: 'Mali', label: 'Mali' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Martinique', label: 'Martinique' },
    { value: 'Mauritania', label: 'Mauritania' },
    { value: 'Mauritius', label: 'Mauritius' },
    { value: 'Mayotte', label: 'Mayotte' },
    { value: 'Mexico', label: 'Mexico' },
    { value: 'Moldova, Republic of', label: 'Moldova, Republic of' },
    { value: 'Monaco', label: 'Monaco' },
    { value: 'Mongolia', label: 'Mongolia' },
    { value: 'Montenegro', label: 'Montenegro' },
    { value: 'Montserrat', label: 'Montserrat' },
    { value: 'Morocco', label: 'Morocco' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Namibia', label: 'Namibia' },
    { value: 'Nepal', label: 'Nepal' },
    { value: 'Netherlands', label: 'Netherlands' },
    { value: 'New Zealand', label: 'New Zealand' },
    { value: 'Nicaragua', label: 'Nicaragua' },
    { value: 'Niger', label: 'Niger' },
    { value: 'Nigeria', label: 'Nigeria' },
    { value: 'Korea, Democratic Republic of (North Korea)', label: 'Korea, Democratic Republic of (North Korea)' },
    { value: 'Norway', label: 'Norway' },
    { value: 'Oman', label: 'Oman' },
    { value: 'Pacific Islands', label: 'Pacific Islands' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'Panama', label: 'Panama' },
    { value: 'Papua New Guinea', label: 'Papua New Guinea' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Peru', label: 'Peru' },
    { value: 'Philippines', label: 'Philippines' },
    { value: 'Poland', label: 'Poland' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Puerto Rico', label: 'Puerto Rico' },
    { value: 'Qatar', label: 'Qatar' },
    { value: 'Reunion', label: 'Reunion' },
    { value: 'Romania', label: 'Romania' },
    { value: 'Russian Federation', label: 'Russian Federation' },
    { value: 'Rwanda', label: 'Rwanda' },
    { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
    { value: 'Saint Lucia', label: 'Saint Lucia' },
    { value: 'Saint Vincent\'s & Grenadines', label: 'Saint Vincent\'s & Grenadines' },
    { value: 'Samoa', label: 'Samoa' },
    { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
    { value: 'Saudi Arabia', label: 'Saudi Arabia' },
    { value: 'Senegal', label: 'Senegal' },
    { value: 'Serbia', label: 'Serbia' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Sierra Leone', label: 'Sierra Leone' },
    { value: 'Singapore', label: 'Singapore' },
    { value: 'Slovak Republic (Slovakia)', label: 'Slovak Republic (Slovakia)' },
    { value: 'Slovenia', label: 'Slovenia' },
    { value: 'Solomon Islands', label: 'Solomon Islands' },
    { value: 'Somalia', label: 'Somalia' },
    { value: 'South Africa', label: 'South Africa' },
    { value: 'Korea, Republic of (South Korea)', label: 'Korea, Republic of (South Korea)' },
    { value: 'South Sudan', label: 'South Sudan' },
    { value: 'Spain', label: 'Spain' },
    { value: 'Sri Lanka', label: 'Sri Lanka' },
    { value: 'Sudan', label: 'Sudan' },
    { value: 'Suriname', label: 'Suriname' },
    { value: 'Swaziland', label: 'Swaziland' },
    { value: 'Sweden', label: 'Sweden' },
    { value: 'Switzerland', label: 'Switzerland' },
    { value: 'Syria', label: 'Syria' },
    { value: 'Tajikistan', label: 'Tajikistan' },
    { value: 'Tanzania', label: 'Tanzania' },
    { value: 'Thailand', label: 'Thailand' },
    { value: 'Timor Leste', label: 'Timor Leste' },
    { value: 'Togo', label: 'Togo' },
    { value: 'Trinidad & Tobago', label: 'Trinidad & Tobago' },
    { value: 'Tunisia', label: 'Tunisia' },
    { value: 'Turkey', label: 'Turkey' },
    { value: 'Turkmenistan', label: 'Turkmenistan' },
    { value: 'Turks & Caicos Islands', label: 'Turks & Caicos Islands' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Ukraine', label: 'Ukraine' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates' },
    { value: 'United States of America (USA)', label: 'United States of America (USA)' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Uzbekistan', label: 'Uzbekistan' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'Virgin Islands (UK)', label: 'Virgin Islands (UK)' },
    { value: 'Virgin Islands (US)', label: 'Virgin Islands (US)' },
    { value: 'Yemen', label: 'Yemen' },
    { value: 'Zambia', label: 'Zambia' },
    { value: 'Zimbabwe', label: 'Zimbabwe' }
  ]
}
